# /plataforma_uptc/docker-compose.yml

services:
  auth_service:
    build: ./auth_service
    env_file:
      - ./auth_service/.env
    volumes:
      - ./auth_service/app:/code/app
    ports: 
      - "8000:8000"

  api_gateway:
    build: ./api_gateway
    ports:
      - "80:80"
    depends_on:
      - auth_service